[default]
python_file_name = "src//qjm_lindblad_base.py"
group_name = "fig3b_T2_gamma_0929"
run_name = "{timestamp}"
nh = true
initial_state = "mixture"
theta = 0.0
phi = 0.0
k0 = 0.5
n_momentum_points = 13
n_particles = 6
n_savesteps = 51
n_trajectories = 512
batch_size = 64
jumps_per_step = 4
gamma = 0.32
T2 = 0.8
temperature = 0.0
sim_time = 2.0
seed = 0

[[simulations]]
run_name = "sim_0_0{timestamp}"
T2 = 0.4
gamma = 0.18

[[simulations]]
run_name = "sim_0_1{timestamp}"
T2 = 0.4
gamma = 0.32

[[simulations]]
run_name = "sim_0_2{timestamp}"
T2 = 0.4
gamma = 1.0

[[simulations]]
run_name = "sim_1_0{timestamp}"
T2 = 0.8
gamma = 0.18

[[simulations]]
run_name = "sim_1_1{timestamp}"
T2 = 0.8
gamma = 0.32

[[simulations]]
run_name = "sim_1_2{timestamp}"
T2 = 0.8
gamma = 1.0

[[simulations]]
run_name = "sim_2_0{timestamp}"
T2 = 2.0
gamma = 0.18

[[simulations]]
run_name = "sim_2_1{timestamp}"
T2 = 2.0
gamma = 0.32

[[simulations]]
run_name = "sim_2_2{timestamp}"
T2 = 2.0
gamma = 1.0

[[simulations]]
run_name = "sim_3_0{timestamp}"
T2 = 1000000.0
gamma = 0.18

[[simulations]]
run_name = "sim_3_1{timestamp}"
T2 = 1000000.0
gamma = 0.32

[[simulations]]
run_name = "sim_3_2{timestamp}"
T2 = 1000000.0
gamma = 1.0