[default]
python_file_name = "src//qjm_lindblad_base.py"
group_name = "fig4c0920"
run_name = "{timestamp}"
nh = true
initial_state = "mixture"
theta = 0.0
phi = 0.0
n_momentum_points = 13
n_particles = 6
n_savesteps = 101
n_trajectories = 512
batch_size = 64
jumps_per_step = 4
gamma = 0.36
T2 = 1.0
temperature = 0.0
sim_time = 4.0
seed = 0

[[simulations]]
run_name = "sim0_{timestamp}"
gamma = 0.34

[[simulations]]
run_name = "sim0_{timestamp}"
gamma = 0.36

[[simulations]]
run_name = "sim0_{timestamp}"
gamma = 0.38