[default]
python_file_name = "src//qjm_lindblad_base.py"
group_name = "fig4c0925_fermi_lower"
run_name = "{timestamp}"
nh = true
initial_state = "soc_ground"
theta = 0.0
phi = 0.0
k0 = 1.0
n_momentum_points = 11
n_particles = 8
n_savesteps = 101
n_trajectories = 512
batch_size = 64
jumps_per_step = 20
gamma = 0.32
T2 = 0.8
temperature = 0.0
sim_time = 4.0
seed = 0

[[simulations]]
run_name = "sim0_{timestamp}"
T2 = 0.2

[[simulations]]
run_name = "sim1_{timestamp}"
T2 = 0.8

[[simulations]]
run_name = "sim2_{timestamp}"
T2 = 1.5

[[simulations]]
run_name = "sim3_{timestamp}"
T2 = 4.0

[[simulations]]
run_name = "sim4_{timestamp}"
T2 = 1000000.0